[run]
timeout = "120s"

[output]
format = "colored-line-number"

[linters]
enable = [
    "gocyclo", "unconvert", "goimports", "unused", "varcheck", "vetshadow",
    "misspell", "nakedret", "errcheck", "revive", "ineffassign", "deadcode",
    "goconst", "vet", "unparam", "gofumpt", "prealloc", "gomnd", "gocritic"
]

[issues]
exclude-use-default = false
