name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: run semantic-release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
